import { client } from "../api/libs/client";
import classes from "../blog/id.module.css"
import Head from 'next/head'
import { Main } from '@/components/Main'
import { Header } from '@/components/Header/header'
import { Footer } from '@/components/Footer/footer'
import { Pagination } from "@/components/Pagenation/pagenation";

export default function BlogId({ data, blog, totalCount }) {
    return (
        <div>
            <Head>
                <title>Contents Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Main page="BlogContents" blog={blog} totalCount={totalCount} comp={<Pagination totalCount={totalCount} blogid={blog} />} pagecomp={<div>
                <div>
                    <h1 className={classes.title}>{data.title}</h1>
                    <p className={classes.publishedtime}>{data.publishedAt}</p>
                    <div className={classes.content_container}
                        dangerouslySetInnerHTML={{
                            __html: `${data.content}`,
                        }}
                    />
                </div>
            </div>} />
            <Footer />
        </div>
    );
}

export const getStaticPaths = async () => {
    const data = await client.get({ endpoint: "blog" });

    const range = (start, end) => [...Array(end - start + 1)].map((_, i) => start + i);

    const paths = data.contents.map((content) => `/blog/${content.id}`);

    return { paths, fallback: true };
};

export const getStaticProps = async (context) => {
    const id = context.params.id
    const data = await client.get({ endpoint: "blog", contentId: id });
    const bloginfo = await client.get({ endpoint: "blog", queries: { offset: 0, limit: 5 } });

    return {
        props: {
            data,
            blog: bloginfo.contents,
            totalCount: bloginfo.totalCount
        },
    };
};