import Head from 'next/head'
import { Main } from '@/components/Main'
import { Header } from '@/components/Header/header'
import { Footer } from '@/components/Footer/footer'
import { ContactForm } from '@/components/Contact/contactform'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main page="Contact"/>
      <ContactForm />
      <Footer />
    </div>
  )
}