import Head from 'next/head'
import { Footer } from '@/components/Footer/footer'
import { Main } from '@/components/Main'
import { Header } from '@/components/Header/header'
import { useAuth0 } from "@auth0/auth0-react";

const RedirectToLogin = () => {
  const { isAuthenticated,loginWithRedirect } = useAuth0();
  loginWithRedirect({
    authorizationParams: {
      redirect_uri: "http://localhost:3000"
    }
  });
  return <></>;
};

export default function Home() {
  const { isAuthenticated, isLoading, logout } = useAuth0();
  return (
    <div>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      {isAuthenticated ? (
        //認証済み時はログイン後の画面を表示
        <div className="App">
          <header className="App-header">
            <button
              onClick={() => {
                logout({ returnTo: window.location.origin });
              }}
            >
              Log out
            </button>
            <img src={logo} className="App-logo" alt="logo" />
            <p>
              Edit <code>src/App.tsx</code> and save to reload.
            </p>
            <a
              className="App-link"
              href="https://reactjs.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              Learn React
            </a>
          </header>
        </div>
      ) : isLoading ? (
        //ログイン試行中はローディング画面を表示
        <div>Loading...</div>
      ) : (
        //未認証時はAuth0のログイン画面にリダイレクト
        <RedirectToLogin />
      )}
      <Footer />
    </div>
  )
}