import { Footer } from "@/components/Footer/footer";
import { Header } from "@/components/Header/header";
import dynamic from "next/dynamic";
import Head from "next/head";
import React from "react";
import { useMemo } from "react";

function MapPage() {
    const Map = useMemo(
        () =>
            dynamic(() => import("../components/Map/map"), {
                loading: () => <p>A map is loading</p>,
                ssr: false,
            }),
        []
    );
    return (
        <div>
            <Head>
                <title>Map Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Map />
            <Footer />
        </div>
    )
}

export default MapPage;